package org.kuali.rice.kim.v2_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-02-12T14:45:09.927-05:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://rice.kuali.org/kim/v2_0", name = "identityService")
@XmlSeeAlso({org.kuali.rice.core.v2_0.ObjectFactory.class, ObjectFactory.class})
public interface IdentityService {

    @WebMethod
    @RequestWrapper(localName = "addAffiliationToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddAffiliationToEntity")
    @ResponseWrapper(localName = "addAffiliationToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddAffiliationToEntityResponse")
    public void addAffiliationToEntity(
        @WebParam(mode = WebParam.Mode.INOUT, name = "affiliation", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityAffiliationType> affiliation
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getPrincipalResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public GetPrincipalResponse getPrincipal(
        @WebParam(partName = "parameters", name = "getPrincipal", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        GetPrincipal parameters
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getPrincipalByPrincipalNameAndPasswordResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public GetPrincipalByPrincipalNameAndPasswordResponse getPrincipalByPrincipalNameAndPassword(
        @WebParam(partName = "parameters", name = "getPrincipalByPrincipalNameAndPassword", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        GetPrincipalByPrincipalNameAndPassword parameters
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "updateAffiliation", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateAffiliation")
    @ResponseWrapper(localName = "updateAffiliationResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateAffiliationResponse")
    public void updateAffiliation(
        @WebParam(mode = WebParam.Mode.INOUT, name = "affiliation", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityAffiliationType> affiliation
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "updateEmployment", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateEmployment")
    @ResponseWrapper(localName = "updateEmploymentResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateEmploymentResponse")
    public void updateEmployment(
        @WebParam(mode = WebParam.Mode.INOUT, name = "employment", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityEmploymentType> employment
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "addNameToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddNameToEntity")
    @ResponseWrapper(localName = "addNameToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddNameToEntityResponse")
    public void addNameToEntity(
        @WebParam(mode = WebParam.Mode.INOUT, name = "name", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityNameType> name
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "getEmailType", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEmailType")
    @ResponseWrapper(localName = "getEmailTypeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEmailTypeResponse")
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.CodedAttributeType getEmailType(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String code
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "addAddressToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddAddressToEntity")
    @ResponseWrapper(localName = "addAddressToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddAddressToEntityResponse")
    public void addAddressToEntity(
        @WebParam(mode = WebParam.Mode.INOUT, name = "address", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityAddressType> address
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "findAllAddressTypes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllAddressTypes")
    @ResponseWrapper(localName = "findAllAddressTypesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllAddressTypesResponse")
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public java.util.List<org.kuali.rice.kim.v2_0.CodedAttributeType> findAllAddressTypes();

    @WebMethod
    @RequestWrapper(localName = "findEntityDefaults", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindEntityDefaults")
    @ResponseWrapper(localName = "findEntityDefaultsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindEntityDefaultsResponse")
    @WebResult(name = "results", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.EntityDefaultQueryResultsType findEntityDefaults(
        @WebParam(name = "query", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        org.kuali.rice.core.v2_0.QueryByCriteriaType query
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getEntityDefaultByPrincipalIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public GetEntityDefaultByPrincipalIdResponse getEntityDefaultByPrincipalId(
        @WebParam(partName = "parameters", name = "getEntityDefaultByPrincipalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        GetEntityDefaultByPrincipalId parameters
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getEntityDefaultByPrincipalNameResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public GetEntityDefaultByPrincipalNameResponse getEntityDefaultByPrincipalName(
        @WebParam(partName = "parameters", name = "getEntityDefaultByPrincipalName", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        GetEntityDefaultByPrincipalName parameters
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "addCitizenshipToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddCitizenshipToEntity")
    @ResponseWrapper(localName = "addCitizenshipToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddCitizenshipToEntityResponse")
    public void addCitizenshipToEntity(
        @WebParam(mode = WebParam.Mode.INOUT, name = "citizenship", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityCitizenshipType> citizenship
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "findAllEmploymentStatuses", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllEmploymentStatuses")
    @ResponseWrapper(localName = "findAllEmploymentStatusesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllEmploymentStatusesResponse")
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public java.util.List<org.kuali.rice.kim.v2_0.CodedAttributeType> findAllEmploymentStatuses();

    @WebMethod
    @RequestWrapper(localName = "findAllCitizenshipStatuses", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllCitizenshipStatuses")
    @ResponseWrapper(localName = "findAllCitizenshipStatusesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllCitizenshipStatusesResponse")
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public java.util.List<org.kuali.rice.kim.v2_0.CodedAttributeType> findAllCitizenshipStatuses();

    @WebMethod
    @RequestWrapper(localName = "getDefaultNamesForPrincipalIds", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetDefaultNamesForPrincipalIds")
    @ResponseWrapper(localName = "getDefaultNamesForPrincipalIdsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetDefaultNamesForPrincipalIdsResponse")
    @WebResult(name = "entityNamePrincipalNames", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.GetDefaultNamesForPrincipalIdsResponse.EntityNamePrincipalNames getDefaultNamesForPrincipalIds(
        @WebParam(name = "principalIds", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.util.List<java.lang.String> principalIds
    );

    @WebMethod
    @RequestWrapper(localName = "getEmploymentType", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEmploymentType")
    @ResponseWrapper(localName = "getEmploymentTypeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEmploymentTypeResponse")
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.CodedAttributeType getEmploymentType(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String code
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "updateExternalIdentifier", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateExternalIdentifier")
    @ResponseWrapper(localName = "updateExternalIdentifierResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateExternalIdentifierResponse")
    public void updateExternalIdentifier(
        @WebParam(mode = WebParam.Mode.INOUT, name = "externalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityExternalIdentifierType> externalId
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "getEntityPrivacyPreferences", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityPrivacyPreferences")
    @ResponseWrapper(localName = "getEntityPrivacyPreferencesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityPrivacyPreferencesResponse")
    @WebResult(name = "privacyPreferences", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.EntityPrivacyPreferencesType getEntityPrivacyPreferences(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String id
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "updateAddress", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateAddress")
    @ResponseWrapper(localName = "updateAddressResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateAddressResponse")
    public void updateAddress(
        @WebParam(mode = WebParam.Mode.INOUT, name = "address", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityAddressType> address
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "addPhoneToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddPhoneToEntity")
    @ResponseWrapper(localName = "addPhoneToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddPhoneToEntityResponse")
    public void addPhoneToEntity(
        @WebParam(mode = WebParam.Mode.INOUT, name = "phone", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityPhoneType> phone
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "getAffiliationType", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetAffiliationType")
    @ResponseWrapper(localName = "getAffiliationTypeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetAffiliationTypeResponse")
    @WebResult(name = "affiliationType", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.EntityAffiliationTypeType getAffiliationType(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String code
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "getExternalIdentifierType", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetExternalIdentifierType")
    @ResponseWrapper(localName = "getExternalIdentifierTypeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetExternalIdentifierTypeResponse")
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.EntityExternalIdentifierTypeType getExternalIdentifierType(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String code
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "getPrincipalsByEmployeeId", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipalsByEmployeeId")
    @ResponseWrapper(localName = "getPrincipalsByEmployeeIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipalsByEmployeeIdResponse")
    @WebResult(name = "principals", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public java.util.List<org.kuali.rice.kim.v2_0.PrincipalType> getPrincipalsByEmployeeId(
        @WebParam(name = "employeeId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String employeeId
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "inactivatePrincipalResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public InactivatePrincipalResponse inactivatePrincipal(
        @WebParam(partName = "parameters", name = "inactivatePrincipal", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        InactivatePrincipal parameters
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "addResidencyToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddResidencyToEntity")
    @ResponseWrapper(localName = "addResidencyToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddResidencyToEntityResponse")
    public void addResidencyToEntity(
        @WebParam(mode = WebParam.Mode.INOUT, name = "residency", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityResidencyType> residency
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "getPhoneType", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPhoneType")
    @ResponseWrapper(localName = "getPhoneTypeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPhoneTypeResponse")
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.CodedAttributeType getPhoneType(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String code
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "inactivateEmail", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateEmail")
    @ResponseWrapper(localName = "inactivateEmailResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateEmailResponse")
    @WebResult(name = "email", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.EntityEmailType inactivateEmail(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String id
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "inactivateCitizenship", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateCitizenship")
    @ResponseWrapper(localName = "inactivateCitizenshipResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateCitizenshipResponse")
    @WebResult(name = "citizenship", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.EntityCitizenshipType inactivateCitizenship(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String id
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "inactivatePhone", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivatePhone")
    @ResponseWrapper(localName = "inactivatePhoneResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivatePhoneResponse")
    @WebResult(name = "phone", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.EntityPhoneType inactivatePhone(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String id
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "updateEmail", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateEmail")
    @ResponseWrapper(localName = "updateEmailResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateEmailResponse")
    public void updateEmail(
        @WebParam(mode = WebParam.Mode.INOUT, name = "email", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityEmailType> email
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "updateEntityTypeContactInfoResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public UpdateEntityTypeContactInfoResponse updateEntityTypeContactInfo(
        @WebParam(partName = "parameters", name = "updateEntityTypeContactInfo", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        UpdateEntityTypeContactInfo parameters
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "updateEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public UpdateEntityResponse updateEntity(
        @WebParam(partName = "parameters", name = "updateEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        UpdateEntity parameters
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "getEmploymentStatus", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEmploymentStatus")
    @ResponseWrapper(localName = "getEmploymentStatusResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEmploymentStatusResponse")
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.CodedAttributeType getEmploymentStatus(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String code
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "inactivateEntityTypeContactInfoResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public InactivateEntityTypeContactInfoResponse inactivateEntityTypeContactInfo(
        @WebParam(partName = "parameters", name = "inactivateEntityTypeContactInfo", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        InactivateEntityTypeContactInfo parameters
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getEntityByEmployeeIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public GetEntityByEmployeeIdResponse getEntityByEmployeeId(
        @WebParam(partName = "parameters", name = "getEntityByEmployeeId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        GetEntityByEmployeeId parameters
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "inactivateEmployment", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateEmployment")
    @ResponseWrapper(localName = "inactivateEmploymentResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateEmploymentResponse")
    @WebResult(name = "employment", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.EntityEmploymentType inactivateEmployment(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String id
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "updatePrincipalResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public UpdatePrincipalResponse updatePrincipal(
        @WebParam(partName = "parameters", name = "updatePrincipal", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        UpdatePrincipal parameters
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "getAddressType", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetAddressType")
    @ResponseWrapper(localName = "getAddressTypeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetAddressTypeResponse")
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.CodedAttributeType getAddressType(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String code
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getPrincipalByPrincipalNameResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public GetPrincipalByPrincipalNameResponse getPrincipalByPrincipalName(
        @WebParam(partName = "parameters", name = "getPrincipalByPrincipalName", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        GetPrincipalByPrincipalName parameters
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "updateResidency", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateResidency")
    @ResponseWrapper(localName = "updateResidencyResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateResidencyResponse")
    public void updateResidency(
        @WebParam(mode = WebParam.Mode.INOUT, name = "residency", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityResidencyType> residency
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "findAllExternalIdentifierTypeTypes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllExternalIdentifierTypeTypes")
    @ResponseWrapper(localName = "findAllExternalIdentifierTypeTypesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllExternalIdentifierTypeTypesResponse")
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public java.util.List<org.kuali.rice.kim.v2_0.EntityExternalIdentifierTypeType> findAllExternalIdentifierTypeTypes();

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "addEntityTypeContactInfoToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public AddEntityTypeContactInfoToEntityResponse addEntityTypeContactInfoToEntity(
        @WebParam(partName = "parameters", name = "addEntityTypeContactInfoToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        AddEntityTypeContactInfoToEntity parameters
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "updateEthnicity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateEthnicity")
    @ResponseWrapper(localName = "updateEthnicityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateEthnicityResponse")
    public void updateEthnicity(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ethnicity", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityEthnicityType> ethnicity
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "createEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public CreateEntityResponse createEntity(
        @WebParam(partName = "parameters", name = "createEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        CreateEntity parameters
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "updateName", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateName")
    @ResponseWrapper(localName = "updateNameResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateNameResponse")
    public void updateName(
        @WebParam(mode = WebParam.Mode.INOUT, name = "name", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityNameType> name
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "addEmailToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddEmailToEntity")
    @ResponseWrapper(localName = "addEmailToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddEmailToEntityResponse")
    public void addEmailToEntity(
        @WebParam(mode = WebParam.Mode.INOUT, name = "email", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityEmailType> email
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "getPrincipalsByEntityId", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipalsByEntityId")
    @ResponseWrapper(localName = "getPrincipalsByEntityIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipalsByEntityIdResponse")
    @WebResult(name = "principals", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public java.util.List<org.kuali.rice.kim.v2_0.PrincipalType> getPrincipalsByEntityId(
        @WebParam(name = "entityId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String entityId
    );

    @WebMethod
    @RequestWrapper(localName = "getNameType", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetNameType")
    @ResponseWrapper(localName = "getNameTypeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetNameTypeResponse")
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.CodedAttributeType getNameType(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String code
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "findAllPhoneTypes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllPhoneTypes")
    @ResponseWrapper(localName = "findAllPhoneTypesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllPhoneTypesResponse")
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public java.util.List<org.kuali.rice.kim.v2_0.CodedAttributeType> findAllPhoneTypes();

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "inactivatePrincipalByNameResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public InactivatePrincipalByNameResponse inactivatePrincipalByName(
        @WebParam(partName = "parameters", name = "inactivatePrincipalByName", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        InactivatePrincipalByName parameters
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getEntityByPrincipalNameResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public GetEntityByPrincipalNameResponse getEntityByPrincipalName(
        @WebParam(partName = "parameters", name = "getEntityByPrincipalName", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        GetEntityByPrincipalName parameters
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "addPrincipalToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public AddPrincipalToEntityResponse addPrincipalToEntity(
        @WebParam(partName = "parameters", name = "addPrincipalToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        AddPrincipalToEntity parameters
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "inactivateEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public InactivateEntityResponse inactivateEntity(
        @WebParam(partName = "parameters", name = "inactivateEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        InactivateEntity parameters
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "updatePhone", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdatePhone")
    @ResponseWrapper(localName = "updatePhoneResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdatePhoneResponse")
    public void updatePhone(
        @WebParam(mode = WebParam.Mode.INOUT, name = "phone", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityPhoneType> phone
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "findAllAffiliationTypes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllAffiliationTypes")
    @ResponseWrapper(localName = "findAllAffiliationTypesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllAffiliationTypesResponse")
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public java.util.List<org.kuali.rice.kim.v2_0.EntityAffiliationTypeType> findAllAffiliationTypes();

    @WebMethod
    @RequestWrapper(localName = "inactivateAddress", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateAddress")
    @ResponseWrapper(localName = "inactivateAddressResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateAddressResponse")
    @WebResult(name = "address", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.EntityAddressType inactivateAddress(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String id
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "addPrivacyPreferencesToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddPrivacyPreferencesToEntity")
    @ResponseWrapper(localName = "addPrivacyPreferencesToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddPrivacyPreferencesToEntityResponse")
    public void addPrivacyPreferencesToEntity(
        @WebParam(mode = WebParam.Mode.INOUT, name = "privacyPreferences", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityPrivacyPreferencesType> privacyPreferences
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "inactivateAffiliation", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateAffiliation")
    @ResponseWrapper(localName = "inactivateAffiliationResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateAffiliationResponse")
    @WebResult(name = "affiliation", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.EntityAffiliationType inactivateAffiliation(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String id
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getPrivacyPreferencesForPrincipalIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public GetPrivacyPreferencesForPrincipalIdResponse getPrivacyPreferencesForPrincipalId(
        @WebParam(partName = "parameters", name = "getPrivacyPreferencesForPrincipalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        GetPrivacyPreferencesForPrincipalId parameters
    );

    @WebMethod
    @RequestWrapper(localName = "updateCitizenship", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateCitizenship")
    @ResponseWrapper(localName = "updateCitizenshipResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateCitizenshipResponse")
    public void updateCitizenship(
        @WebParam(mode = WebParam.Mode.INOUT, name = "citizenship", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityCitizenshipType> citizenship
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getEntityDefaultResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public GetEntityDefaultResponse getEntityDefault(
        @WebParam(partName = "parameters", name = "getEntityDefault", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        GetEntityDefault parameters
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "addBioDemographicsToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddBioDemographicsToEntity")
    @ResponseWrapper(localName = "addBioDemographicsToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddBioDemographicsToEntityResponse")
    public void addBioDemographicsToEntity(
        @WebParam(mode = WebParam.Mode.INOUT, name = "bioDemographics", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityBioDemographicsType> bioDemographics
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "addEmploymentToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddEmploymentToEntity")
    @ResponseWrapper(localName = "addEmploymentToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddEmploymentToEntityResponse")
    public void addEmploymentToEntity(
        @WebParam(mode = WebParam.Mode.INOUT, name = "employment", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityEmploymentType> employment
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getEntityByPrincipalIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public GetEntityByPrincipalIdResponse getEntityByPrincipalId(
        @WebParam(partName = "parameters", name = "getEntityByPrincipalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        GetEntityByPrincipalId parameters
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "inactivateName", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateName")
    @ResponseWrapper(localName = "inactivateNameResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.InactivateNameResponse")
    @WebResult(name = "name", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.EntityNameType inactivateName(
        @WebParam(name = "id", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String id
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "updateBioDemographics", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateBioDemographics")
    @ResponseWrapper(localName = "updateBioDemographicsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateBioDemographicsResponse")
    public void updateBioDemographics(
        @WebParam(mode = WebParam.Mode.INOUT, name = "bioDemographics", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityBioDemographicsType> bioDemographics
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "findEntities", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindEntities")
    @ResponseWrapper(localName = "findEntitiesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindEntitiesResponse")
    @WebResult(name = "results", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.EntityQueryResultsType findEntities(
        @WebParam(name = "query", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        org.kuali.rice.core.v2_0.QueryByCriteriaType query
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "updateVisa", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateVisa")
    @ResponseWrapper(localName = "updateVisaResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdateVisaResponse")
    public void updateVisa(
        @WebParam(mode = WebParam.Mode.INOUT, name = "visa", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityVisaType> visa
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "findPrincipals", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindPrincipals")
    @ResponseWrapper(localName = "findPrincipalsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindPrincipalsResponse")
    @WebResult(name = "results", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.PrincipalQueryResultsType findPrincipals(
        @WebParam(name = "query", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        org.kuali.rice.core.v2_0.QueryByCriteriaType query
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "updatePrivacyPreferences", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdatePrivacyPreferences")
    @ResponseWrapper(localName = "updatePrivacyPreferencesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.UpdatePrivacyPreferencesResponse")
    public void updatePrivacyPreferences(
        @WebParam(mode = WebParam.Mode.INOUT, name = "privacyPreferences", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityPrivacyPreferencesType> privacyPreferences
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "addVisaToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddVisaToEntity")
    @ResponseWrapper(localName = "addVisaToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddVisaToEntityResponse")
    public void addVisaToEntity(
        @WebParam(mode = WebParam.Mode.INOUT, name = "visa", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityVisaType> visa
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "findAllEmailTypes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllEmailTypes")
    @ResponseWrapper(localName = "findAllEmailTypesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllEmailTypesResponse")
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public java.util.List<org.kuali.rice.kim.v2_0.CodedAttributeType> findAllEmailTypes();

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getEntityDefaultByEmployeeIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public GetEntityDefaultByEmployeeIdResponse getEntityDefaultByEmployeeId(
        @WebParam(partName = "parameters", name = "getEntityDefaultByEmployeeId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        GetEntityDefaultByEmployeeId parameters
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "getCitizenshipStatus", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetCitizenshipStatus")
    @ResponseWrapper(localName = "getCitizenshipStatusResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetCitizenshipStatusResponse")
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.CodedAttributeType getCitizenshipStatus(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String code
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getDefaultNamesForPrincipalIdResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public GetDefaultNamesForPrincipalIdResponse getDefaultNamesForPrincipalId(
        @WebParam(partName = "parameters", name = "getDefaultNamesForPrincipalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        GetDefaultNamesForPrincipalId parameters
    );

    @WebMethod
    @RequestWrapper(localName = "addEthnicityToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddEthnicityToEntity")
    @ResponseWrapper(localName = "addEthnicityToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddEthnicityToEntityResponse")
    public void addEthnicityToEntity(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ethnicity", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityEthnicityType> ethnicity
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "addExternalIdentifierToEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddExternalIdentifierToEntity")
    @ResponseWrapper(localName = "addExternalIdentifierToEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.AddExternalIdentifierToEntityResponse")
    public void addExternalIdentifierToEntity(
        @WebParam(mode = WebParam.Mode.INOUT, name = "externalId", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        javax.xml.ws.Holder<EntityExternalIdentifierType> externalId
    ) throws RiceIllegalArgumentException, RiceIllegalStateException;

    @WebMethod
    @RequestWrapper(localName = "findAllEntityTypes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllEntityTypes")
    @ResponseWrapper(localName = "findAllEntityTypesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllEntityTypesResponse")
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public java.util.List<org.kuali.rice.kim.v2_0.CodedAttributeType> findAllEntityTypes();

    @WebMethod
    @RequestWrapper(localName = "findAllEmploymentTypes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllEmploymentTypes")
    @ResponseWrapper(localName = "findAllEmploymentTypesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllEmploymentTypesResponse")
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public java.util.List<org.kuali.rice.kim.v2_0.CodedAttributeType> findAllEmploymentTypes();

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getEntityResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", partName = "parameters")
    public GetEntityResponse getEntity(
        @WebParam(partName = "parameters", name = "getEntity", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        GetEntity parameters
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "getPrincipals", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipals")
    @ResponseWrapper(localName = "getPrincipalsResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetPrincipalsResponse")
    @WebResult(name = "ret", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public java.util.List<org.kuali.rice.kim.v2_0.PrincipalType> getPrincipals(
        @WebParam(name = "principalIds", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.util.List<java.lang.String> principalIds
    );

    @WebMethod
    @RequestWrapper(localName = "findAllNameTypes", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllNameTypes")
    @ResponseWrapper(localName = "findAllNameTypesResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.FindAllNameTypesResponse")
    @WebResult(name = "types", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public java.util.List<org.kuali.rice.kim.v2_0.CodedAttributeType> findAllNameTypes();

    @WebMethod
    @RequestWrapper(localName = "getEntityType", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityType")
    @ResponseWrapper(localName = "getEntityTypeResponse", targetNamespace = "http://rice.kuali.org/kim/v2_0", className = "org.kuali.rice.kim.v2_0.GetEntityTypeResponse")
    @WebResult(name = "type", targetNamespace = "http://rice.kuali.org/kim/v2_0")
    public org.kuali.rice.kim.v2_0.CodedAttributeType getEntityType(
        @WebParam(name = "code", targetNamespace = "http://rice.kuali.org/kim/v2_0")
        java.lang.String code
    ) throws RiceIllegalArgumentException;
}
