
package org.kuali.rice.kim.v2_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-02-12T14:45:09.919-05:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "IllegalArgumentFault", targetNamespace = "http://rice.kuali.org/core/v2_0")
public class RiceIllegalArgumentException extends Exception {
    
    private org.kuali.rice.core.v2_0.IllegalArgumentFault illegalArgumentFault;

    public RiceIllegalArgumentException() {
        super();
    }
    
    public RiceIllegalArgumentException(String message) {
        super(message);
    }
    
    public RiceIllegalArgumentException(String message, Throwable cause) {
        super(message, cause);
    }

    public RiceIllegalArgumentException(String message, org.kuali.rice.core.v2_0.IllegalArgumentFault illegalArgumentFault) {
        super(message);
        this.illegalArgumentFault = illegalArgumentFault;
    }

    public RiceIllegalArgumentException(String message, org.kuali.rice.core.v2_0.IllegalArgumentFault illegalArgumentFault, Throwable cause) {
        super(message, cause);
        this.illegalArgumentFault = illegalArgumentFault;
    }

    public org.kuali.rice.core.v2_0.IllegalArgumentFault getFaultInfo() {
        return this.illegalArgumentFault;
    }
}
