NSERT INTO KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','U10221699',SYSDATE,sys_guid(),1);

INSERT INTO KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,PRNCPL_PSWD,VER_NBR)
  VALUES ('Y','U10221699',SYSDATE,sys_guid(),'U10221699','iruiz',null,1);

INSERT INTO KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','U10221699','PERSON',SYSDATE,sys_guid(),1);


INSERT INTO KRIM_ENTITY_AFLTN_T (ENTITY_AFLTN_ID,OBJ_ID,VER_NBR,ENTITY_ID,AFLTN_TYP_CD,CAMPUS_CD,DFLT_IND,ACTV_IND,LAST_UPDT_DT)
  VALUES (KRIM_ENTITY_AFLTN_ID_S.NEXTVAL,sys_guid(),1,'U10221699','0002','21','Y','Y',sysdate);

INSERT INTO KRIM_ENTITY_EMP_INFO_T (ENTITY_EMP_ID,OBJ_ID,VER_NBR,ENTITY_ID,ENTITY_AFLTN_ID,EMP_STAT_CD,EMP_TYP_CD,BASE_SLRY_AMT,ACTV_IND,LAST_UPDT_DT,PRMRY_DEPT_CD,PRMRY_IND,EMP_REC_ID)
  VALUES (KRIM_ENTITY_EMP_ID_S.NEXTVAL,sys_guid(),1,'U10221699',KRIM_ENTITY_AFLTN_ID_S.CURRVAL,'3','6',0,'Y',SYSDATE,'2570450000','Y',null);

INSERT INTO KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,MIDDLE_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','U10221699',KRIM_ENTITY_NM_ID_S.NEXTVAL,'IRENE',null,'RUIZ GALLEGO',SYSDATE,'PRFR',null,1);

INSERT INTO KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','IRUIZ@BU.EDU','WRK',KRIM_ENTITY_EMAIL_ID_S.NEXTVAL,'U10221699','PERSON',SYSDATE,sys_guid(),1);