package org.kuali.rice.kim.v2_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-02-13T15:51:15.747-05:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "identityService", 
                  wsdlLocation = "file:/Users/mukadder/git/kuali-research22/coeus-impl/src/main/resources/edu/bu/kuali/kra/wsdl/SI_KCRM_PROCESS_OUTBOUND_v9.wsdl",
                  targetNamespace = "http://rice.kuali.org/kim/v2_0") 
public class IdentityService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://rice.kuali.org/kim/v2_0", "identityService");
    public final static QName IdentityServicePort = new QName("http://rice.kuali.org/kim/v2_0", "identityServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/mukadder/git/kuali-research22/coeus-impl/src/main/resources/edu/bu/kuali/kra/wsdl/SI_KCRM_PROCESS_OUTBOUND_v9.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IdentityService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/mukadder/git/kuali-research22/coeus-impl/src/main/resources/edu/bu/kuali/kra/wsdl/SI_KCRM_PROCESS_OUTBOUND_v9.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IdentityService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IdentityService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IdentityService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IdentityService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IdentityService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IdentityService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IdentityService
     */
    @WebEndpoint(name = "identityServicePort")
    public IdentityService getIdentityServicePort() {
        return super.getPort(IdentityServicePort, IdentityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IdentityService
     */
    @WebEndpoint(name = "identityServicePort")
    public IdentityService getIdentityServicePort(WebServiceFeature... features) {
        return super.getPort(IdentityServicePort, IdentityService.class, features);
    }

}
