
package org.kuali.rice.kim.v2_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-02-13T15:51:15.734-05:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "IllegalStateFault", targetNamespace = "http://rice.kuali.org/core/v2_0")
public class RiceIllegalStateException extends Exception {
    
    private org.kuali.rice.core.v2_0.IllegalStateFault illegalStateFault;

    public RiceIllegalStateException() {
        super();
    }
    
    public RiceIllegalStateException(String message) {
        super(message);
    }
    
    public RiceIllegalStateException(String message, Throwable cause) {
        super(message, cause);
    }

    public RiceIllegalStateException(String message, org.kuali.rice.core.v2_0.IllegalStateFault illegalStateFault) {
        super(message);
        this.illegalStateFault = illegalStateFault;
    }

    public RiceIllegalStateException(String message, org.kuali.rice.core.v2_0.IllegalStateFault illegalStateFault, Throwable cause) {
        super(message, cause);
        this.illegalStateFault = illegalStateFault;
    }

    public org.kuali.rice.core.v2_0.IllegalStateFault getFaultInfo() {
        return this.illegalStateFault;
    }
}
