package com.example.testSoap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class VEFEntityBioDemographicsType extends AttributeContainer implements KvmSerializable
{

    
    public String entityId;
    
    public String deceasedDate;
    
    public String birthDate;
    
    public Integer age=0;
    
    public String genderCode;
    
    public String genderChangeCode;
    
    public String maritalStatusCode;
    
    public String primaryLanguageCode;
    
    public String secondaryLanguageCode;
    
    public String birthCountry;
    
    public String birthStateProvinceCode;
    
    public String birthCity;
    
    public String geographicOrigin;
    
    public String birthDateUnmasked;
    
    public String genderCodeUnmasked;
    
    public String genderChangeCodeUnmasked;
    
    public String maritalStatusCodeUnmasked;
    
    public String primaryLanguageCodeUnmasked;
    
    public String secondaryLanguageCodeUnmasked;
    
    public String birthCountryUnmasked;
    
    public String birthStateProvinceCodeUnmasked;
    
    public String birthCityUnmasked;
    
    public String geographicOriginUnmasked;
    
    public String noteMessage;
    
    public Boolean suppressPersonal=false;
    
    public Long versionNumber;
    
    public String objectId;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,VEFExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,VEFExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("entityId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.entityId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.entityId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("deceasedDate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.deceasedDate = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.deceasedDate = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("birthDate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.birthDate = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.birthDate = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("age"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.age = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.age = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("genderCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.genderCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.genderCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("genderChangeCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.genderChangeCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.genderChangeCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("maritalStatusCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.maritalStatusCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.maritalStatusCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("primaryLanguageCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.primaryLanguageCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.primaryLanguageCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("secondaryLanguageCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.secondaryLanguageCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.secondaryLanguageCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("birthCountry"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.birthCountry = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.birthCountry = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("birthStateProvinceCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.birthStateProvinceCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.birthStateProvinceCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("birthCity"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.birthCity = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.birthCity = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("geographicOrigin"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.geographicOrigin = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.geographicOrigin = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("birthDateUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.birthDateUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.birthDateUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("genderCodeUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.genderCodeUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.genderCodeUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("genderChangeCodeUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.genderChangeCodeUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.genderChangeCodeUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("maritalStatusCodeUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.maritalStatusCodeUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.maritalStatusCodeUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("primaryLanguageCodeUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.primaryLanguageCodeUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.primaryLanguageCodeUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("secondaryLanguageCodeUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.secondaryLanguageCodeUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.secondaryLanguageCodeUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("birthCountryUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.birthCountryUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.birthCountryUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("birthStateProvinceCodeUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.birthStateProvinceCodeUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.birthStateProvinceCodeUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("birthCityUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.birthCityUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.birthCityUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("geographicOriginUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.geographicOriginUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.geographicOriginUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("noteMessage"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.noteMessage = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.noteMessage = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("suppressPersonal"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.suppressPersonal = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.suppressPersonal = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("versionNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.versionNumber = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.versionNumber = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("objectId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.objectId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.objectId = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.entityId!=null?this.entityId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.deceasedDate!=null?this.deceasedDate:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.birthDate!=null?this.birthDate:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return age;
        }
        if(propertyIndex==4)
        {
            return this.genderCode!=null?this.genderCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.genderChangeCode!=null?this.genderChangeCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.maritalStatusCode!=null?this.maritalStatusCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.primaryLanguageCode!=null?this.primaryLanguageCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.secondaryLanguageCode!=null?this.secondaryLanguageCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.birthCountry!=null?this.birthCountry:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.birthStateProvinceCode!=null?this.birthStateProvinceCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.birthCity!=null?this.birthCity:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.geographicOrigin!=null?this.geographicOrigin:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.birthDateUnmasked!=null?this.birthDateUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.genderCodeUnmasked!=null?this.genderCodeUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.genderChangeCodeUnmasked!=null?this.genderChangeCodeUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.maritalStatusCodeUnmasked!=null?this.maritalStatusCodeUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.primaryLanguageCodeUnmasked!=null?this.primaryLanguageCodeUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.secondaryLanguageCodeUnmasked!=null?this.secondaryLanguageCodeUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==19)
        {
            return this.birthCountryUnmasked!=null?this.birthCountryUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==20)
        {
            return this.birthStateProvinceCodeUnmasked!=null?this.birthStateProvinceCodeUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==21)
        {
            return this.birthCityUnmasked!=null?this.birthCityUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==22)
        {
            return this.geographicOriginUnmasked!=null?this.geographicOriginUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==23)
        {
            return this.noteMessage!=null?this.noteMessage:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==24)
        {
            return suppressPersonal;
        }
        if(propertyIndex==25)
        {
            return this.versionNumber!=null?this.versionNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==26)
        {
            return this.objectId!=null?this.objectId:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 27;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "entityId";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "deceasedDate";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "birthDate";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "age";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "genderCode";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "genderChangeCode";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "maritalStatusCode";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "primaryLanguageCode";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "secondaryLanguageCode";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "birthCountry";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "birthStateProvinceCode";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "birthCity";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "geographicOrigin";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "birthDateUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "genderCodeUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "genderChangeCodeUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "maritalStatusCodeUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "primaryLanguageCodeUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "secondaryLanguageCodeUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "birthCountryUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==20)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "birthStateProvinceCodeUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==21)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "birthCityUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==22)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "geographicOriginUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "noteMessage";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==24)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "suppressPersonal";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==25)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "versionNumber";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==26)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "objectId";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

