package com.example.testSoap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class VEFEntityTypeContactInfoType extends AttributeContainer implements KvmSerializable
{

    
    public String entityId;
    
    public String entityTypeCode;
    
    public VEFCodedAttributeType entityType;
    
    public VEFEntityTypeContactInfoType_addresses addresses;
    
    public VEFEntityTypeContactInfoType_emailAddresses emailAddresses;
    
    public VEFEntityTypeContactInfoType_phoneNumbers phoneNumbers;
    
    public VEFEntityAddressType defaultAddress;
    
    public VEFEntityEmailType defaultEmailAddress;
    
    public VEFEntityPhoneType defaultPhoneNumber;
    
    public Long versionNumber;
    
    public String objectId;
    
    public Boolean active=false;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,VEFExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,VEFExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("entityId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.entityId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.entityId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("entityTypeCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.entityTypeCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.entityTypeCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("entityType"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.entityType = (VEFCodedAttributeType)__envelope.get(j,VEFCodedAttributeType.class,false);
            }
            return true;
        }
        if (info.name.equals("addresses"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.addresses = (VEFEntityTypeContactInfoType_addresses)__envelope.get(j,VEFEntityTypeContactInfoType_addresses.class,false);
            }
            return true;
        }
        if (info.name.equals("emailAddresses"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.emailAddresses = (VEFEntityTypeContactInfoType_emailAddresses)__envelope.get(j,VEFEntityTypeContactInfoType_emailAddresses.class,false);
            }
            return true;
        }
        if (info.name.equals("phoneNumbers"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.phoneNumbers = (VEFEntityTypeContactInfoType_phoneNumbers)__envelope.get(j,VEFEntityTypeContactInfoType_phoneNumbers.class,false);
            }
            return true;
        }
        if (info.name.equals("defaultAddress"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.defaultAddress = (VEFEntityAddressType)__envelope.get(j,VEFEntityAddressType.class,false);
            }
            return true;
        }
        if (info.name.equals("defaultEmailAddress"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.defaultEmailAddress = (VEFEntityEmailType)__envelope.get(j,VEFEntityEmailType.class,false);
            }
            return true;
        }
        if (info.name.equals("defaultPhoneNumber"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.defaultPhoneNumber = (VEFEntityPhoneType)__envelope.get(j,VEFEntityPhoneType.class,false);
            }
            return true;
        }
        if (info.name.equals("versionNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.versionNumber = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.versionNumber = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("objectId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.objectId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.objectId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("active"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.active = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.active = (Boolean)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return entityId;
        }
        if(propertyIndex==1)
        {
            return entityTypeCode;
        }
        if(propertyIndex==2)
        {
            return this.entityType!=null?this.entityType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.addresses!=null?this.addresses:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.emailAddresses!=null?this.emailAddresses:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.phoneNumbers!=null?this.phoneNumbers:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.defaultAddress!=null?this.defaultAddress:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.defaultEmailAddress!=null?this.defaultEmailAddress:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.defaultPhoneNumber!=null?this.defaultPhoneNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.versionNumber!=null?this.versionNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.objectId!=null?this.objectId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return active;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 12;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "entityId";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "entityTypeCode";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==2)
        {
            info.type = VEFCodedAttributeType.class;
            info.name = "entityType";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "addresses";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "emailAddresses";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "phoneNumbers";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==6)
        {
            info.type = VEFEntityAddressType.class;
            info.name = "defaultAddress";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==7)
        {
            info.type = VEFEntityEmailType.class;
            info.name = "defaultEmailAddress";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==8)
        {
            info.type = VEFEntityPhoneType.class;
            info.name = "defaultPhoneNumber";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "versionNumber";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "objectId";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "active";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

