package com.example.testSoap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class VEFEntityAddressType extends AttributeContainer implements KvmSerializable
{

    
    public String id;
    
    public String entityTypeCode;
    
    public String entityId;
    
    public VEFCodedAttributeType addressType;
    
    public String attentionLine;
    
    public String line1;
    
    public String line2;
    
    public String line3;
    
    public String city;
    
    public String stateProvinceCode;
    
    public String postalCode;
    
    public String countryCode;
    
    public String attentionLineUnmasked;
    
    public String line1Unmasked;
    
    public String line2Unmasked;
    
    public String line3Unmasked;
    
    public String cityUnmasked;
    
    public String stateProvinceCodeUnmasked;
    
    public String postalCodeUnmasked;
    
    public String countryCodeUnmasked;
    
    public String addressFormat;
    
    public java.util.Date modifiedDate;
    
    public java.util.Date validatedDate;
    
    public Boolean validated=false;
    
    public String noteMessage;
    
    public Boolean suppressAddress=false;
    
    public Boolean defaultValue=false;
    
    public Boolean active=false;
    
    public Long versionNumber;
    
    public String objectId;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,VEFExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,VEFExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("id"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.id = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.id = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("entityTypeCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.entityTypeCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.entityTypeCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("entityId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.entityId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.entityId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("addressType"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.addressType = (VEFCodedAttributeType)__envelope.get(j,VEFCodedAttributeType.class,false);
            }
            return true;
        }
        if (info.name.equals("attentionLine"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.attentionLine = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.attentionLine = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("line1"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.line1 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.line1 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("line2"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.line2 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.line2 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("line3"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.line3 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.line3 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("city"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.city = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.city = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("stateProvinceCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.stateProvinceCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.stateProvinceCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("postalCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.postalCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.postalCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("countryCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.countryCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.countryCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("attentionLineUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.attentionLineUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.attentionLineUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("line1Unmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.line1Unmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.line1Unmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("line2Unmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.line2Unmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.line2Unmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("line3Unmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.line3Unmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.line3Unmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("cityUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cityUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cityUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("stateProvinceCodeUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.stateProvinceCodeUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.stateProvinceCodeUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("postalCodeUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.postalCodeUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.postalCodeUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("countryCodeUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.countryCodeUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.countryCodeUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("addressFormat"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.addressFormat = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.addressFormat = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("modifiedDate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.modifiedDate = VEFHelper.ConvertFromWebService(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.modifiedDate = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("validatedDate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.validatedDate = VEFHelper.ConvertFromWebService(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.validatedDate = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("validated"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.validated = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.validated = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("noteMessage"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.noteMessage = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.noteMessage = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("suppressAddress"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.suppressAddress = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.suppressAddress = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("defaultValue"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.defaultValue = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.defaultValue = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("active"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.active = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.active = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("versionNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.versionNumber = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.versionNumber = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("objectId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.objectId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.objectId = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.id!=null?this.id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.entityTypeCode!=null?this.entityTypeCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.entityId!=null?this.entityId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.addressType!=null?this.addressType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.attentionLine!=null?this.attentionLine:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.line1!=null?this.line1:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.line2!=null?this.line2:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.line3!=null?this.line3:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.city!=null?this.city:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.stateProvinceCode!=null?this.stateProvinceCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.postalCode!=null?this.postalCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.countryCode!=null?this.countryCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.attentionLineUnmasked!=null?this.attentionLineUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.line1Unmasked!=null?this.line1Unmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.line2Unmasked!=null?this.line2Unmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.line3Unmasked!=null?this.line3Unmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.cityUnmasked!=null?this.cityUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.stateProvinceCodeUnmasked!=null?this.stateProvinceCodeUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.postalCodeUnmasked!=null?this.postalCodeUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==19)
        {
            return this.countryCodeUnmasked!=null?this.countryCodeUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==20)
        {
            return this.addressFormat!=null?this.addressFormat:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==21)
        {
            return this.modifiedDate!=null?VEFHelper.getDateTimeFormat().format(this.modifiedDate):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==22)
        {
            return this.validatedDate!=null?VEFHelper.getDateTimeFormat().format(this.validatedDate):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==23)
        {
            return validated;
        }
        if(propertyIndex==24)
        {
            return this.noteMessage!=null?this.noteMessage:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==25)
        {
            return suppressAddress;
        }
        if(propertyIndex==26)
        {
            return defaultValue;
        }
        if(propertyIndex==27)
        {
            return active;
        }
        if(propertyIndex==28)
        {
            return this.versionNumber!=null?this.versionNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==29)
        {
            return this.objectId!=null?this.objectId:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 30;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "id";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "entityTypeCode";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "entityId";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==3)
        {
            info.type = VEFCodedAttributeType.class;
            info.name = "addressType";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "attentionLine";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "line1";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "line2";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "line3";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "city";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "stateProvinceCode";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "postalCode";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "countryCode";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "attentionLineUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "line1Unmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "line2Unmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "line3Unmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cityUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "stateProvinceCodeUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "postalCodeUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "countryCodeUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==20)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "addressFormat";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==21)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "modifiedDate";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==22)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "validatedDate";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "validated";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==24)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "noteMessage";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==25)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "suppressAddress";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==26)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "defaultValue";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==27)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "active";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==28)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "versionNumber";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==29)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "objectId";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

