package com.example.testSoap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class VEFEntityEmploymentType extends AttributeContainer implements KvmSerializable
{

    
    public String id;
    
    public String entityId;
    
    public String employeeId;
    
    public String employmentRecordId;
    
    public VEFEntityAffiliationType entityAffiliation;
    
    public VEFCodedAttributeType employeeStatus;
    
    public VEFCodedAttributeType employeeType;
    
    public String primaryDepartmentCode;
    
    public String baseSalaryAmount;
    
    public Boolean primary=false;
    
    public Long versionNumber;
    
    public String objectId;
    
    public Boolean active=false;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,VEFExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,VEFExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("id"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.id = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.id = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("entityId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.entityId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.entityId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("employeeId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.employeeId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.employeeId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("employmentRecordId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.employmentRecordId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.employmentRecordId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("entityAffiliation"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.entityAffiliation = (VEFEntityAffiliationType)__envelope.get(j,VEFEntityAffiliationType.class,false);
            }
            return true;
        }
        if (info.name.equals("employeeStatus"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.employeeStatus = (VEFCodedAttributeType)__envelope.get(j,VEFCodedAttributeType.class,false);
            }
            return true;
        }
        if (info.name.equals("employeeType"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.employeeType = (VEFCodedAttributeType)__envelope.get(j,VEFCodedAttributeType.class,false);
            }
            return true;
        }
        if (info.name.equals("primaryDepartmentCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.primaryDepartmentCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.primaryDepartmentCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("baseSalaryAmount"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.baseSalaryAmount = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.baseSalaryAmount = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("primary"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.primary = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.primary = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("versionNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.versionNumber = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.versionNumber = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("objectId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.objectId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.objectId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("active"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.active = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.active = (Boolean)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.id!=null?this.id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.entityId!=null?this.entityId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.employeeId!=null?this.employeeId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.employmentRecordId!=null?this.employmentRecordId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return entityAffiliation;
        }
        if(propertyIndex==5)
        {
            return this.employeeStatus!=null?this.employeeStatus:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.employeeType!=null?this.employeeType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.primaryDepartmentCode!=null?this.primaryDepartmentCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.baseSalaryAmount!=null?this.baseSalaryAmount:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return primary;
        }
        if(propertyIndex==10)
        {
            return this.versionNumber!=null?this.versionNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.objectId!=null?this.objectId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return active;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 13;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "id";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "entityId";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "employeeId";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "employmentRecordId";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==4)
        {
            info.type = VEFEntityAffiliationType.class;
            info.name = "entityAffiliation";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==5)
        {
            info.type = VEFCodedAttributeType.class;
            info.name = "employeeStatus";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==6)
        {
            info.type = VEFCodedAttributeType.class;
            info.name = "employeeType";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "primaryDepartmentCode";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "baseSalaryAmount";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "primary";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "versionNumber";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "objectId";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "active";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

