package com.example.testSoap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class VEFEntityTypeDataDefaultType extends AttributeContainer implements KvmSerializable
{

    
    public String entityTypeCode;
    
    public VEFEntityAddressType defaultAddress;
    
    public VEFEntityEmailType defaultEmailAddress;
    
    public VEFEntityPhoneType defaultPhoneNumber;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,VEFExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,VEFExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("entityTypeCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.entityTypeCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.entityTypeCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("defaultAddress"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.defaultAddress = (VEFEntityAddressType)__envelope.get(j,VEFEntityAddressType.class,false);
            }
            return true;
        }
        if (info.name.equals("defaultEmailAddress"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.defaultEmailAddress = (VEFEntityEmailType)__envelope.get(j,VEFEntityEmailType.class,false);
            }
            return true;
        }
        if (info.name.equals("defaultPhoneNumber"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.defaultPhoneNumber = (VEFEntityPhoneType)__envelope.get(j,VEFEntityPhoneType.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return entityTypeCode;
        }
        if(propertyIndex==1)
        {
            return this.defaultAddress!=null?this.defaultAddress:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.defaultEmailAddress!=null?this.defaultEmailAddress:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.defaultPhoneNumber!=null?this.defaultPhoneNumber:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "entityTypeCode";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==1)
        {
            info.type = VEFEntityAddressType.class;
            info.name = "defaultAddress";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==2)
        {
            info.type = VEFEntityEmailType.class;
            info.name = "defaultEmailAddress";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==3)
        {
            info.type = VEFEntityPhoneType.class;
            info.name = "defaultPhoneNumber";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

