package com.example.testSoap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class VEFEntityType extends AttributeContainer implements KvmSerializable
{

    
    public String id;
    
    public VEFEntityType_principals principals;
    
    public VEFEntityType_entityTypeContactInfos entityTypeContactInfos;
    
    public VEFEntityType_externalIdentifiers externalIdentifiers;
    
    public VEFEntityType_affiliations affiliations;
    
    public VEFEntityType_names names;
    
    public VEFEntityType_employmentInformation employmentInformation;
    
    public VEFEntityPrivacyPreferencesType privacyPreferences;
    
    public VEFEntityBioDemographicsType bioDemographics;
    
    public VEFEntityType_citizenships citizenships;
    
    public VEFEntityEmploymentType primaryEmployment;
    
    public VEFEntityAffiliationType defaultAffiliation;
    
    public VEFEntityNameType defaultName;
    
    public VEFEntityType_ethnicities ethnicities;
    
    public VEFEntityType_residencies residencies;
    
    public VEFEntityType_visas visas;
    
    public Long versionNumber;
    
    public String objectId;
    
    public Boolean active=false;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,VEFExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,VEFExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("id"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.id = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.id = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("principals"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.principals = (VEFEntityType_principals)__envelope.get(j,VEFEntityType_principals.class,false);
            }
            return true;
        }
        if (info.name.equals("entityTypeContactInfos"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.entityTypeContactInfos = (VEFEntityType_entityTypeContactInfos)__envelope.get(j,VEFEntityType_entityTypeContactInfos.class,false);
            }
            return true;
        }
        if (info.name.equals("externalIdentifiers"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.externalIdentifiers = (VEFEntityType_externalIdentifiers)__envelope.get(j,VEFEntityType_externalIdentifiers.class,false);
            }
            return true;
        }
        if (info.name.equals("affiliations"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.affiliations = (VEFEntityType_affiliations)__envelope.get(j,VEFEntityType_affiliations.class,false);
            }
            return true;
        }
        if (info.name.equals("names"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.names = (VEFEntityType_names)__envelope.get(j,VEFEntityType_names.class,false);
            }
            return true;
        }
        if (info.name.equals("employmentInformation"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.employmentInformation = (VEFEntityType_employmentInformation)__envelope.get(j,VEFEntityType_employmentInformation.class,false);
            }
            return true;
        }
        if (info.name.equals("privacyPreferences"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.privacyPreferences = (VEFEntityPrivacyPreferencesType)__envelope.get(j,VEFEntityPrivacyPreferencesType.class,false);
            }
            return true;
        }
        if (info.name.equals("bioDemographics"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.bioDemographics = (VEFEntityBioDemographicsType)__envelope.get(j,VEFEntityBioDemographicsType.class,false);
            }
            return true;
        }
        if (info.name.equals("citizenships"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.citizenships = (VEFEntityType_citizenships)__envelope.get(j,VEFEntityType_citizenships.class,false);
            }
            return true;
        }
        if (info.name.equals("primaryEmployment"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.primaryEmployment = (VEFEntityEmploymentType)__envelope.get(j,VEFEntityEmploymentType.class,false);
            }
            return true;
        }
        if (info.name.equals("defaultAffiliation"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.defaultAffiliation = (VEFEntityAffiliationType)__envelope.get(j,VEFEntityAffiliationType.class,false);
            }
            return true;
        }
        if (info.name.equals("defaultName"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.defaultName = (VEFEntityNameType)__envelope.get(j,VEFEntityNameType.class,false);
            }
            return true;
        }
        if (info.name.equals("ethnicities"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ethnicities = (VEFEntityType_ethnicities)__envelope.get(j,VEFEntityType_ethnicities.class,false);
            }
            return true;
        }
        if (info.name.equals("residencies"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.residencies = (VEFEntityType_residencies)__envelope.get(j,VEFEntityType_residencies.class,false);
            }
            return true;
        }
        if (info.name.equals("visas"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.visas = (VEFEntityType_visas)__envelope.get(j,VEFEntityType_visas.class,false);
            }
            return true;
        }
        if (info.name.equals("versionNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.versionNumber = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.versionNumber = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("objectId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.objectId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.objectId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("active"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.active = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.active = (Boolean)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.id!=null?this.id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.principals!=null?this.principals:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.entityTypeContactInfos!=null?this.entityTypeContactInfos:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.externalIdentifiers!=null?this.externalIdentifiers:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.affiliations!=null?this.affiliations:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.names!=null?this.names:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.employmentInformation!=null?this.employmentInformation:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.privacyPreferences!=null?this.privacyPreferences:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.bioDemographics!=null?this.bioDemographics:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.citizenships!=null?this.citizenships:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.primaryEmployment!=null?this.primaryEmployment:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.defaultAffiliation!=null?this.defaultAffiliation:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.defaultName!=null?this.defaultName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.ethnicities!=null?this.ethnicities:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.residencies!=null?this.residencies:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.visas!=null?this.visas:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.versionNumber!=null?this.versionNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.objectId!=null?this.objectId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return active;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 19;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "id";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "principals";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "entityTypeContactInfos";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "externalIdentifiers";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "affiliations";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "names";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "employmentInformation";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==7)
        {
            info.type = VEFEntityPrivacyPreferencesType.class;
            info.name = "privacyPreferences";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==8)
        {
            info.type = VEFEntityBioDemographicsType.class;
            info.name = "bioDemographics";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "citizenships";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==10)
        {
            info.type = VEFEntityEmploymentType.class;
            info.name = "primaryEmployment";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==11)
        {
            info.type = VEFEntityAffiliationType.class;
            info.name = "defaultAffiliation";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==12)
        {
            info.type = VEFEntityNameType.class;
            info.name = "defaultName";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "ethnicities";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "residencies";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "visas";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "versionNumber";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "objectId";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "active";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

