package com.example.testSoap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class VEFEntityNameType extends AttributeContainer implements KvmSerializable
{

    
    public String id;
    
    public String entityId;
    
    public VEFCodedAttributeType nameType;
    
    public String namePrefix;
    
    public String nameTitle;
    
    public String firstName;
    
    public String middleName;
    
    public String lastName;
    
    public String nameSuffix;
    
    public String compositeName;
    
    public String namePrefixUnmasked;
    
    public String nameTitleUnmasked;
    
    public String firstNameUnmasked;
    
    public String middleNameUnmasked;
    
    public String lastNameUnmasked;
    
    public String nameSuffixUnmasked;
    
    public String compositeNameUnmasked;
    
    public String noteMessage;
    
    public java.util.Date nameChangedDate;
    
    public Boolean suppressName=false;
    
    public Boolean defaultValue=false;
    
    public Boolean active=false;
    
    public Long versionNumber;
    
    public String objectId;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,VEFExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,VEFExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("id"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.id = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.id = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("entityId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.entityId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.entityId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("nameType"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.nameType = (VEFCodedAttributeType)__envelope.get(j,VEFCodedAttributeType.class,false);
            }
            return true;
        }
        if (info.name.equals("namePrefix"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.namePrefix = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.namePrefix = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("nameTitle"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.nameTitle = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.nameTitle = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("firstName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.firstName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.firstName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("middleName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.middleName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.middleName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("lastName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.lastName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.lastName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("nameSuffix"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.nameSuffix = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.nameSuffix = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("compositeName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.compositeName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.compositeName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("namePrefixUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.namePrefixUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.namePrefixUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("nameTitleUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.nameTitleUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.nameTitleUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("firstNameUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.firstNameUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.firstNameUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("middleNameUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.middleNameUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.middleNameUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("lastNameUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.lastNameUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.lastNameUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("nameSuffixUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.nameSuffixUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.nameSuffixUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("compositeNameUnmasked"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.compositeNameUnmasked = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.compositeNameUnmasked = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("noteMessage"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.noteMessage = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.noteMessage = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("nameChangedDate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.nameChangedDate = VEFHelper.ConvertFromWebService(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.nameChangedDate = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("suppressName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.suppressName = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.suppressName = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("defaultValue"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.defaultValue = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.defaultValue = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("active"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.active = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.active = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("versionNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.versionNumber = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.versionNumber = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("objectId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.objectId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.objectId = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.id!=null?this.id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.entityId!=null?this.entityId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.nameType!=null?this.nameType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.namePrefix!=null?this.namePrefix:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.nameTitle!=null?this.nameTitle:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.firstName!=null?this.firstName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.middleName!=null?this.middleName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.lastName!=null?this.lastName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.nameSuffix!=null?this.nameSuffix:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.compositeName!=null?this.compositeName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.namePrefixUnmasked!=null?this.namePrefixUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.nameTitleUnmasked!=null?this.nameTitleUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.firstNameUnmasked!=null?this.firstNameUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.middleNameUnmasked!=null?this.middleNameUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.lastNameUnmasked!=null?this.lastNameUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.nameSuffixUnmasked!=null?this.nameSuffixUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.compositeNameUnmasked!=null?this.compositeNameUnmasked:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.noteMessage!=null?this.noteMessage:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.nameChangedDate!=null?VEFHelper.getDateTimeFormat().format(this.nameChangedDate):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==19)
        {
            return suppressName;
        }
        if(propertyIndex==20)
        {
            return defaultValue;
        }
        if(propertyIndex==21)
        {
            return active;
        }
        if(propertyIndex==22)
        {
            return this.versionNumber!=null?this.versionNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==23)
        {
            return this.objectId!=null?this.objectId:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 24;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "id";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "entityId";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==2)
        {
            info.type = VEFCodedAttributeType.class;
            info.name = "nameType";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "namePrefix";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nameTitle";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "firstName";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "middleName";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "lastName";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nameSuffix";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "compositeName";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "namePrefixUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nameTitleUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "firstNameUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "middleNameUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "lastNameUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nameSuffixUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "compositeNameUnmasked";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "noteMessage";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nameChangedDate";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "suppressName";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==20)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "defaultValue";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==21)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "active";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==22)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "versionNumber";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "objectId";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

