package com.example.testSoap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class VEFentityDefaultQueryResultsType extends AttributeContainer implements KvmSerializable
{

    
    public VEFentityDefaultQueryResultsType_results results;
    
    public Integer totalRowCount;
    
    public Boolean moreResultsAvailable=false;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,VEFExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,VEFExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("results"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.results = (VEFentityDefaultQueryResultsType_results)__envelope.get(j,VEFentityDefaultQueryResultsType_results.class,false);
            }
            return true;
        }
        if (info.name.equals("totalRowCount"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.totalRowCount = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.totalRowCount = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("moreResultsAvailable"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.moreResultsAvailable = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.moreResultsAvailable = (Boolean)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.results!=null?this.results:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.totalRowCount!=null?this.totalRowCount:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return moreResultsAvailable;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "results";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "totalRowCount";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "moreResultsAvailable";
            info.namespace= "http://rice.kuali.org/kim/v2_0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

